#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

build()
{
    tag=${1:-}
    branch=${2:-}
    base=${3:-}

    docker build \
        --build-arg YOCTO_BUILDER_BASE=${base} \
        --build-arg IOTG_YOCTO_BRANCH=${branch} \
        ${DOCKER_BUILD_OPTS:-} \
        -t ${DOCKER_REPO}:${tag} .
}

if [ $# -eq 0 ]; then
    build latest e3900/mater xenial-warrior
    build mr5b03 MR5-B-03 xenial-warrior
    build mr5b02 MR5-B-02 xenial-warrior
    build mr5b01 MR5-B-01 xenial-warrior
    build mr4b02 MR4-B-02 trusty-sumo
    build mr4b01 MR4-B-01 trusty-sumo
    build mr4rtb01 MR4rt-B-01 trusty-sumo
    build mr4 E3900-MR4 trusty-sumo
    build mr4b E3900-MR4-Beta trusty-sumo
    build mr3.1 E3900-MR3.1 trusty-jethro
else
    build "$@"
fi
