name: Publish Docker image
on:
  push:
  schedule:
    - cron: "40 18 1 * *"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag_branch_base:
          [
            [mr3.1, E3900-MR3.1, trusty-jethro],
            [mr4, E3900-MR4, trusty-sumo],
            [mr4rtb01, MR4rt-B-01, trusty-sumo],
            [mr4b02, MR4-B-02, trusty-sumo],
            [mr5b04, MR5-B-04, xenial-warrior],
            [latest, e3900/mater, xenial-warrior],
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/yocto-iotg-builder
            ghcr.io/anyakichi/yocto-iotg-builder
          tags: ${{ matrix.tag_branch_base[0] }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            base=${{ matrix.tag_branch_base[2] }}
            iotg_yocto_branch=${{ matrix.tag_branch_base[1] }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
